### ISSUE TITLE
DAG is in running state, but none of the tasks are started

### ISSUE THREAD

**Issue by rasikas** [bitnami/bitnami-docker-airflow#36] opened 2020-04-13 09:05 UTC
**Description**

**Steps to reproduce the issue:**

1. get the `docker-compose.yml` as instructed in the `readme`
2. run `docker-compose up`
3. access the web url http://host:8080`
4. enable and execute sample DAG ex: `tutorial` or `example_bash_operator`

**Describe the results you received:**

DAG tasks are queued but never runs. DAG is always at running state, but any of the tasks are not started.

**Describe the results you expected:**

I expect each task of the DAG to complete.

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried this first in my local machine and then with a VM in google cloud as well.

In the docker logs I can see the below section repeating

~~~
airflow_1            | [2020-04-13 08:57:08,255] {security.py:313} INFO - Cleaning faulty perms
airflow_1            | [2020-04-13 08:57:09 +0000] [65] [INFO] Handling signal: ttou
airflow_1            | [2020-04-13 08:57:09 +0000] [82] [INFO] Worker exiting (pid: 82)
airflow_1            | [2020-04-13 08:57:39 +0000] [65] [INFO] Handling signal: ttin
airflow_1            | [2020-04-13 08:57:39 +0000] [87] [INFO] Booting worker with pid: 87
airflow_1            | [2020-04-13 08:57:40,761] {__init__.py:51} INFO - Using executor CeleryExecutor
airflow_1            | [2020-04-13 08:57:40,764] {dagbag.py:403} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags
airflow_1            | [2020-04-13 08:57:41,688] {security.py:461} INFO - Start syncing user roles.
airflow_1            | [2020-04-13 08:57:41,998] {security.py:370} INFO - Fetching a set of all permission, view_menu from F
AB meta-table
airflow_1            | [2020-04-13 08:57:42,358] {security.py:313} INFO - Cleaning faulty perms
airflow_1            | [2020-04-13 08:57:43 +0000] [65] [INFO] Handling signal: ttou
airflow_1            | [2020-04-13 08:57:43 +0000] [83] [INFO] Worker exiting (pid: 83)
airflow_1            | [2020-04-13 08:58:13 +0000] [65] [INFO] Handling signal: ttin
airflow_1            | [2020-04-13 08:58:13 +0000] [88] [INFO] Booting worker with pid: 88
airflow_1            | [2020-04-13 08:58:15,226] {__init__.py:51} INFO - Using executor CeleryExecutor
airflow_1            | [2020-04-13 08:58:15,233] {dagbag.py:403} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags
airflow_1            | [2020-04-13 08:58:15,960] {security.py:461} INFO - Start syncing user roles.
airflow_1            | [2020-04-13 08:58:16,408] {security.py:370} INFO - Fetching a set of all permission, view_menu from F
AB meta-table
~~~

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:26:02 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:36 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-12-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.661GiB
 Name: gcptest
 ID: XCLB:4JTV:QTQI:UPQC:NQ6D:THWK:AVTW:Y2W6:H3FC:3JCY:CYL7:X4JU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Some screenshots

![image](https://user-images.githubusercontent.com/1381205/79108370-8ca0ed80-7db9-11ea-8e6a-52011bd49ba3.png)

![image](https://user-images.githubusercontent.com/1381205/79108401-975b8280-7db9-11ea-8640-17e3498fb408.png)

![image](https://user-images.githubusercontent.com/1381205/79108425-a2aeae00-7db9-11ea-9f93-258b245bd101.png)

**Comment by Mauraza** [comment] 2020-04-13 14:52
Hi @rasikas,

airflow's an application to needs to much a lot of resources, you can see [this](https://github.com/bitnami/charts/issues/1978#issuecomment-600740315) to more information.

**Comment by rasikas** [comment] 2020-04-13 20:49
> Hi @rasikas,
> 
> airflow's an application to needs to much a lot of resources, you can see [this](https://github.com/bitnami/charts/issues/1978#issuecomment-600740315) to more information.

Thank you @Mauraza for the quick reply. Any place I can refer to find the minimum hardware requirements, I anyway spin a bigger VM and see. thanks again for your help

**Comment by rasikas** [comment] 2020-04-14 02:24
@Mauraza I used better configuration with 4cpu and 15GB ram and issue more or less same, please find the errors when I try to run provided sample DAGs, it is hard to think this is related to resources required.

~~~
airflow-scheduler_1  | (Background on this error at: http://sqlalche.me/e/gkpj)
airflow-scheduler_1  | [2020-04-14 02:15:02,416] {__init__.py:56} WARNING - Failed operation [_get_task_meta_for2020-04-14 0
2:15:02,417.  Retrying 0 more times.] {
postgresql_1         | 2020-04-14 02:15:02.416 GMT [512] ERROR:  duplicate key value violates unique constraint "pg_type_typ
name_nsp_index"
postgresql_1         | 2020-04-14 02:15:02.416 GMT [512] DETAIL:  Key (typname, typnamespace)=(celery_tasksetmeta, 2200) alr
eady exists.
postgresql_1         | 2020-04-14 02:15:02.416 GMT [512] STATEMENT:
postgresql_1         |  CREATE TABLE celery_tasksetmeta (
postgresql_1         |          id INTEGER NOT NULL,
postgresql_1         |          taskset_id VARCHAR(155),
postgresql_1         |          result BYTEA,
postgresql_1         |          date_done TIMESTAMP WITHOUT TIME ZONE,
postgresql_1         |          PRIMARY KEY (id),
postgresql_1         |          UNIQUE (taskset_id)
postgresql_1         |  )


airflow-scheduler_1  |     cursor.execute(statement, parameters)
airflow-scheduler_1  | sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique
constraint "pg_type_typname_nsp_index"
airflow-scheduler_1  | DETAIL:  Key (typname, typnamespace)=(celery_tasksetmeta, 2200) already exists.
airflow-scheduler_1  |
airflow-scheduler_1  | [SQL:
airflow-scheduler_1  | CREATE TABLE celery_tasksetmeta (
airflow-scheduler_1  |  id INTEGER NOT NULL,
airflow-scheduler_1  |  taskset_id VARCHAR(155),
airflow-scheduler_1  |  result BYTEA,
airflow-scheduler_1  |  date_done TIMESTAMP WITHOUT TIME ZONE,
airflow-scheduler_1  |  PRIMARY KEY (id),
airflow-scheduler_1  |  UNIQUE (taskset_id)
airflow-scheduler_1  | )
airflow-scheduler_1  |
airflow-scheduler_1  | ]
airflow-scheduler_1  | (Background on this error at: http://sqlalche.me/e/gkpj)
airflow-scheduler_1  |


airflow_1            | [2020-04-14 02:16:18 +0000] [80] [INFO] Handling signal: ttin
airflow_1            | [2020-04-14 02:16:18 +0000] [120] [INFO] Booting worker with pid: 120
airflow_1            | [2020-04-14 02:16:20,291] {__init__.py:51} INFO - Using executor CeleryExecutor
airflow_1            | [2020-04-14 02:16:20,292] {dagbag.py:403} INFO - Filling up the DagBag from /opt/bitnami/airflow/dagsairflow_1            | [2020-04-14 02:16:21,016] {security.py:461} INFO - Start syncing user roles.
airflow_1            | [2020-04-14 02:16:21,313] {security.py:370} INFO - Fetching a set of all permission, view_menu from FAB meta-table
airflow_1            | [2020-04-14 02:16:21,656] {security.py:313} INFO - Cleaning faulty perms
airflow_1            | [2020-04-14 02:16:22 +0000] [80] [INFO] Handling signal: ttou
airflow_1            | [2020-04-14 02:16:22 +0000] [104] [INFO] Worker exiting (pid: 104)
airflow_1            | [2020-04-14 02:16:52 +0000] [80] [INFO] Handling signal: ttin
airflow_1            | [2020-04-14 02:16:52 +0000] [124] [INFO] Booting worker with pid: 124
airflow_1            | [2020-04-14 02:16:53,721] {__init__.py:51} INFO - Using executor CeleryExecutor
airflow_1            | [2020-04-14 02:16:53,722] {dagbag.py:403} INFO - Filling up the DagBag from /opt/bitnami/airflow/dagsairflow_1            | [2020-04-14 02:16:54,483] {security.py:461} INFO - Start syncing user roles.
airflow_1            | [2020-04-14 02:16:54,774] {security.py:370} INFO - Fetching a set of all permission, view_menu from FAB meta-table
airflow_1            | [2020-04-14 02:16:55,114] {security.py:313} INFO - Cleaning faulty perms
airflow_1            | [2020-04-14 02:16:55 +0000] [80] [INFO] Handling signal: ttou
airflow_1            | [2020-04-14 02:16:55 +0000] [108] [INFO] Worker exiting (pid: 108)


B meta-table
airflow_1            | [2020-04-14 02:19:08,970] {security.py:313} INFO - Cleaning faulty perms
airflow_1            | [2020-04-14 02:19:09 +0000] [80] [INFO] Handling signal: ttou
airflow_1            | [2020-04-14 02:19:09 +0000] [124] [INFO] Worker exiting (pid: 124)
airflow_1            | [2020-04-14 02:19:39 +0000] [80] [INFO] Handling signal: ttin
airflow_1            | [2020-04-14 02:19:39 +0000] [144] [INFO] Booting worker with pid: 144
airflow_1            | [2020-04-14 02:19:40,901] {__init__.py:51} INFO - Using executor CeleryExecutor
airflow_1            | [2020-04-14 02:19:40,902] {dagbag.py:403} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags
airflow_1            | [2020-04-14 02:19:41,687] {security.py:461} INFO - Start syncing user roles.
airflow_1            | [2020-04-14 02:19:42,005] {security.py:370} INFO - Fetching a set of all permission, view_menu from FA
B meta-table
airflow_1            | [2020-04-14 02:19:42,432] {security.py:313} INFO - Cleaning faulty perms
airflow_1            | [2020-04-14 02:19:42 +0000] [80] [INFO] Handling signal: ttou
airflow_1            | [2020-04-14 02:19:42 +0000] [128] [INFO] Worker exiting (pid: 128)
airflow_1            | [2020-04-14 02:20:12 +0000] [80] [INFO] Handling signal: ttin
airflow_1            | [2020-04-14 02:20:13 +0000] [148] [INFO] Booting worker with pid: 148
airflow_1            | [2020-04-14 02:20:14,308] {__init__.py:51} INFO - Using executor CeleryExecutor
airflow_1            | [2020-04-14 02:20:14,310] {dagbag.py:403} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags
airflow_1            | [2020-04-14 02:20:15,073] {security.py:461} INFO - Start syncing user roles.
airflow_1            | [2020-04-14 02:20:15,388] {security.py:370} INFO - Fetching a set of all permission, view_menu from FA
B meta-table
~~~

**docker version**
~~~
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
~~~

**docker info**
~~~
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-1033-gcp
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 14.68GiB
 Name: airflowserver
 ID: K2B7:P7BH:2CGE:ZWDC:7B5B:VFZY:BOTF:NCPO:I5GH:OQ6C:FJKS:GIBR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
~~~

**docker-compose version**
~~~
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
~~~

**Comment by Mauraza** [comment] 2020-04-14 07:43
Hi @rasikas,
 
I know it,  I feel the same when I was investigating. 
You seem to have tried to throw the same DAG several times. Could you try throwing one and leave it for a while?. 
Anyway, I'm going to do some more research.

**Comment by rasikas** [comment] 2020-04-14 08:02
@Mauraza i launched only two DAGs, both are very simple ones, those didn't even start. on the other hand if it cannot launch two simultaneously means we have a bigger problem. I think we are missing something here. It can't simply be resource issue at this stage. 

Moreover this error
~~~
onstraint "pg_type_typname_nsp_index"
airflow-scheduler_1  | DETAIL:  Key (typname, typnamespace)=(celery_tasksetmeta, 2200) already exists.
airflow-scheduler_1  |
airflow-scheduler_1  | [SQL:
airflow-scheduler_1  | CREATE TABLE celery_tasksetmeta (
airflow-scheduler_1  |  id INTEGER NOT NULL,
airflow-scheduler_1  |  taskset_id VARCHAR(155),
airflow-scheduler_1  |  result BYTEA,
airflow-scheduler_1  |  date_done TIMESTAMP WITHOUT TIME ZONE,
airflow-scheduler_1  |  PRIMARY KEY (id),
airflow-scheduler_1  |  UNIQUE (taskset_id)
airflow-scheduler_1  | )
airflow-scheduler_1  |
airflow-scheduler_1  | ]
~~~

**Comment by beltran-rubo** [comment] 2020-04-14 13:29
I am confused, from the first screenshots you posted, the jobs ran properly, you can see the latest time executed. You can also trigger them manually from the dashboard. Why do you think the jobs have not been executed?

In your second message you posted an error with the database itself that we can not reproduce it. It looks an issue with duplication keys but from Celery seems that is not a bug just a report from a warning https://github.com/celery/celery/issues/4653

**Comment by rasikas** [comment] 2020-04-14 14:16
@beltran-rubo Jobs are in 'running' state, not a single task inside a job ran, it was like this even after hours. light green color means 'running', dark green means success, if you look the screen shot i shared again you see than not a single task inside started.

![image](https://user-images.githubusercontent.com/1381205/79234896-41b4d200-7eae-11ea-9853-14ad47895419.png)

![image](https://user-images.githubusercontent.com/1381205/79234938-52fdde80-7eae-11ea-8b23-2eaef862d7f3.png)

**Comment by beltran-rubo** [comment] 2020-04-14 14:54
sorry for the confusion. The docker-compose.yaml in this repo do not include the workers right now, try the docker-compose from https://github.com/bitnami/bitnami-docker-airflow-worker 

Sorry for the confusion, we will also add the workers in this repo as well.

**Comment by rasikas** [comment] 2020-04-14 21:20
@beltran-rubo thanks for the direction and the worker image works, and I now can see the dags are running, but unfortunately they fail and can see the following error in the worker logs

~~~sh
[SQL: SELECT task_instance.try_number AS task_instance_try_number, task_instance.task_id AS task_instance_task_id, task_insta
nce.dag_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS
 task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_instance_duration
, task_instance.state AS task_instance_state, task_instance.max_tries AS task_instance_max_tries, task_instance.hostname AS t
ask_instance_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_instance_job_id, task_i
nstance.pool AS task_instance_pool, task_instance.pool_slots AS task_instance_pool_slots, task_instance.queue AS task_instanc
e_queue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator AS task_instance_operator, ta
sk_instance.queued_dttm AS task_instance_queued_dttm, task_instance.pid AS task_instance_pid, task_instance.executor_config A
S task_instance_executor_config
FROM task_instance
WHERE task_instance.dag_id = %(dag_id_1)s AND task_instance.task_id = %(task_id_1)s AND task_instance.execution_date = %(exec
ution_date_1)s
 LIMIT %(param_1)s]
[parameters: {'dag_id_1': 'example_skip_dag', 'task_id_1': 'always_true_1', 'execution_date_1': <Pendulum [2020-04-13T00:00:0
0+00:00]>, 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
[2020-04-14 21:11:55,133] {__init__.py:51} INFO - Using executor CeleryExecutor
[2020-04-14 21:11:55,135] {dagbag.py:396} INFO - Filling up the DagBag from /opt/bitnami/airflow/venv/lib/python3.6/site-pack
ages/airflow/example_dags/example_skip_dag.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column task_instance.pool_slots does not exist
LINE 1: ...job_id, task_instance.pool AS task_instance_pool, task_insta...
                                                             ^
~~~

![image](https://user-images.githubusercontent.com/1381205/79275398-709c6980-7ee9-11ea-95b4-acc906e2728c.png)
Also 'View Log' option shows empty in the UI under each task

Thanks for the support I think I would use [https://github.com/puckel/docker-airflow](https://github.com/puckel/docker-airflow) for the moment which works fine in the first run.

You can close this issue if you think it is just a usage issue from my end. Thanks again

**Comment by beltran-rubo** [comment] 2020-04-15 09:03
Sorry about that. It seems there is a mistmatch with the container versions in the docker-compose.yml file. 

If you specify the image "image: bitnami/airflow-worker:1.10.9" it is working on our side. See jobs are executed successfully:
<img width="1256" alt="Screen Shot 2020-04-15 at 10 50 10" src="https://user-images.githubusercontent.com/3718440/79319214-52923180-7f08-11ea-8589-6077d4fb50df.png">

We will close this issue and update the docker-compose YAML in this repo to include the workers. Thanks for reporting it.

**Closed by beltran-rubo** 2020-04-15 09:03 UTC

**Comment by rasikas** [comment] 2020-04-15 09:12
@beltran-rubo no worries, I will give another try later or when you have the yml updated. Thanks again for your support

**Comment by beltran-rubo** [comment] 2020-04-16 16:25
The docker-compose is now in the repo and the Airflow version has been updated to the latest 1.10.10 as well. Feel free to open a new ticket if you have any questions, thanks.

**Comment by rasikas** [comment] 2020-04-17 02:22
> The docker-compose is now in the repo and the Airflow version has been updated to the latest 1.10.10 as well. Feel free to open a new ticket if you have any questions, thanks.

Thanks @beltran-rubo, May I know which project has the fixed apply?, is it [this repo - bitnami-docker-airflow](https://github.com/bitnami/bitnami-docker-airflow) or the [bitnami-docker-airflow-worker](https://github.com/bitnami/bitnami-docker-airflow-worker)

Which repo should I use (asking this because you asked me to use the bitnami-docker-airflow-worker) project instead of this repo. Thank you

**Comment by beltran-rubo** [comment] 2020-04-17 06:29
Both, now the worker is also included in the docker-compose.yml in the main "airflow" repo.

**Comment by rasikas** [comment] 2020-04-17 08:08
Great, thanks @beltran-rubo
