### ISSUE TITLE
airflow 2 cannot provide some static files

### ISSUE THREAD

**Issue by WqyJh** [bitnami/bitnami-docker-airflow#65] opened 2021-01-19 11:46 UTC
`docker.io/bitnami/airflow:2-debian-10` do not provide some static files. As is shown in the picture, the url of some css files are `/static/` which is wrong. However, `docker.io/bitnami/airflow:1-debian-10` works fine.

![image](https://user-images.githubusercontent.com/15232241/105028919-a1b75500-5a8c-11eb-91f5-c36adec5e8d2.png)

There're only some static files are supported as shown in the following picture which is the contents inside a running airflow 2 container.

![image](https://user-images.githubusercontent.com/15232241/105029287-1d190680-5a8d-11eb-8cde-e5791484d46b.png)

There're much more files inside an airflow 1 container.

![image](https://user-images.githubusercontent.com/15232241/105029720-acbeb500-5a8d-11eb-8392-6af7464cb345.png)

**Steps to reproduce the issue:**

1. [First Step]
This is the content of `docker-compose.yml`, then use `docker-compose up -d` to start the services. The image digest is `2e1e89b5b095`.

```yaml
version: '2'

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:10-debian-10'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    volumes:
      - 'redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2.0.0-debian-10-r1
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    volumes:
      - airflow_scheduler_data:/bitnami
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2-debian-10
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    volumes:
      - airflow_worker_data:/bitnami
  airflow:
    image: docker.io/bitnami/airflow:2-debian-10
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
```
2. [Second Step]
Go to the http://127.0.0.1:8080 and login.

**Comment by andresbono** [comment] 2021-01-19 13:04
Thank you, @WqyJh. We could reproduce the issue and we are currently working on a fix. We will update this issue as soon as a new release of the container is available.

**Comment by WqyJh** [comment] 2021-01-25 09:40
The image of  `bitnami/airflow:1-debian-10` was also encountered with the same problem, probably because of the latest update of the image.

![image](https://user-images.githubusercontent.com/15232241/105687079-ffd3b480-5f32-11eb-9cd9-a7a9381c1f27.png)

My service works fine until I restart it today when k8s pulled the latest image.

![image](https://user-images.githubusercontent.com/15232241/105688247-555c9100-5f34-11eb-8f45-90cfe687be3d.png)

**Comment by andresbono** [comment] 2021-01-25 16:14
Hi @WqyJh, this is very strange, we haven't modified the configuration for Airflow 1. Is it the latest version of Airflow 2 working as expected now?

**Comment by WqyJh** [comment] 2021-01-26 12:40
Yes, it is! Thank you for your works!

**Comment by carrodher** [comment] 2021-01-26 15:43
I am closing this issue since it should be solved in the latest revision of the image. We also improved our testing logic in order to be able to detect similar issues (if any) in the future before releasing the images. Thanks for reporting the issue; feel free to reopen it if something is not working as expected.

**Closed by carrodher** 2021-01-26 15:43 UTC

**Comment by tom-vianai** [comment] 2021-01-28 17:01
The 1.x images were updated to use python 3.8 but seems "FROM bitnami/airflow:1.10.14" is pulling airflow 2 I think and it does not load the static webserver content.

**Comment by carrodher** [comment] 2021-01-29 15:16
What do you mean by "bitnami/airflow:1.10.14 is pulling airflow 2"? The bitnami/airflow:1 and bitnami/airflow:2 are different images; and also its associated rolling tags. You can check that all the rolling tags for the version 1.X are using the same `IMAGE ID`, something similar happens with version 2.X and the `latest` tag:
```console
$ docker images
REPOSITORY                  TAG                     IMAGE ID       CREATED         SIZE
bitnami/airflow             1                       685b62785c90   2 hours ago     954MB
bitnami/airflow             1-debian-10             685b62785c90   2 hours ago     954MB
bitnami/airflow             1.10.14                 685b62785c90   2 hours ago     954MB
bitnami/airflow             2                       9ed53b238066   9 hours ago     1.17GB
bitnami/airflow             2-debian-10             9ed53b238066   9 hours ago     1.17GB
bitnami/airflow             2.0.0                   9ed53b238066   9 hours ago     1.17GB
bitnami/airflow             latest                  9ed53b238066   9 hours ago     1.17GB
```

In the same way, I just deployed the `docker.io/bitnami/airflow:1.10.14` and this is what the "About" page shows:
![Screenshot 2021-01-29 at 16 13 22](https://user-images.githubusercontent.com/13216600/106292670-61569480-624d-11eb-8449-e7a35bbec86c.png)

**Comment by tom-vianai** [comment] 2021-01-29 15:23
I think I understand, but somehow I was pulling bitnami/airflow:1.10.14 and ended up with the airflow 2 UI that just showed the spinning icon for "recent tasks" and "last run" columns....  I have since gone to the 1.10.14-debian-10-r34 image and it seems things may have been fixed as there were check-ins between my 1.10.14 pulls and 1.10.14-debian-10-r34...  I'm trying to clean my image repo and re-init to verify

**Comment by carrodher** [comment] 2021-01-29 15:27
It's really weird, you can run `docker image | grep airflow` and check the ids

**Comment by tom-vianai** [comment] 2021-01-29 20:32
![image](https://user-images.githubusercontent.com/71041093/106315899-e6d04980-6239-11eb-9cc0-b8f17e255d62.png)
This is the new UI from what I can tell, it just sits and spins from what I can research airflow 2.0 builds out a static UI but that is missing.  According to comment above this was fixed in 2.0 images

![image](https://user-images.githubusercontent.com/71041093/106318075-4aa84180-623d-11eb-90c2-3c9a9d75e972.png)

this is the base image I'm pulling from bitnami (FROM bitnami/airflow:1.10.14)

I have now reverted to "FROM bitnami/airflow:1.10.14-debian-10-r28" and I get this error
![image](https://user-images.githubusercontent.com/71041093/106324435-205b8180-6247-11eb-8d69-7dac278fafee.png)
Is there anyway to trigger the static ui build in 1.10 images like someone fixed in the 2.0 images

**Comment by tom-vianai** [comment] 2021-01-29 21:08
I have the same "missing" or incomplete GET "/static/" that is discussed above.  I'm trying to roll back to 1.10.14-debian-10-r1 and see if I get same issues

**Comment by carrodher** [comment] 2021-02-01 16:38
I am not fully understanding the issue, airflow 1 and 2 are following different release processes so it shouldn't be possible to mix tags from airflow 1 and 2, in fact, I double-checked that and each branch is pointing to different images.

Apart from that, during the Airflow 2 releases, we also worked on some improvements (like a new Python version) for both branches, so it is normal the new versions of Airflow 1 also include some changes, but for my manual tests (apart from the automation we have) everything is working fine.

Can you describe what is the current issue with the latest images?

**Comment by StephanZaat** [comment] 2021-02-01 18:05
Actually I'm seeing something similar, although I don't know if it is related to Airflow 2. I'm using the Bitnami Helm chart and needed to upgrade to Python 3.8:

![image](https://user-images.githubusercontent.com/15195218/106498539-d61c0f80-6495-11eb-8eb3-21aa64c5fc09.png)

After startup:
`│ airflow-web INFO  ==> Starting airflow...                                                                                                                                                                │
│ airflow-web   ____________       _____________                                                                                                                                                           │
│ airflow-web  ____    |__( )_________  __/__  /________      __                                                                                                                                           │
│ airflow-web ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /                                                                                                                                           │
│ airflow-web ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /                                                                                                                                            │
│ airflow-web  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/                                                                                                                                             │
│ airflow-web Please make sure to build the frontend in static/ directory and restart the server  `

**Comment by javsalgar** [comment] 2021-02-02 12:44
Hi,

I tried deploying the latest version of the airflow chart and found no issues with the static, as you can see here, it is properly returning the static files

```
+ airflow-web-854d8b469-7z2jq › airflow-web
airflow-web-854d8b469-7z2jq airflow-web 127.0.0.1 - - [02/Feb/2021:12:40:57 +0000] "GET /static/appbuilder/css/bootstrap.min.css HTTP/1.1" 200 0 "http://192.168.201.131:8080/login/?next=http%3A%2F%2F192.168.201.131%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow-web-854d8b469-7z2jq airflow-web 127.0.0.1 - - [02/Feb/2021:12:40:57 +0000] "GET /static/appbuilder/css/font-awesome.min.css HTTP/1.1" 200 0 "http://192.168.201.131:8080/login/?next=http%3A%2F%2F192.168.201.131%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow-web-854d8b469-7z2jq airflow-web 127.0.0.1 - - [02/Feb/2021:12:40:57 +0000] "GET /static/appbuilder/datepicker/bootstrap-datepicker.css HTTP/1.1" 200 0 "http://192.168.201.131:8080/login/?next=http%3A%2F%2F192.168.201.131%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow-web-854d8b469-7z2jq airflow-web 127.0.0.1 - - [02/Feb/2021:12:40:57 +0000] "GET /static/appbuilder/css/ab.css HTTP/1.1" 200 0 "http://192.168.201.131:8080/login/?next=http%3A%2F%2F192.168.201.131%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow-web-854d8b469-7z2jq airflow-web 127.0.0.1 - - [02/Feb/2021:12:40:57 +0000] "GET /static/appbuilder/select2/select2.css HTTP/1.1" 200 0 "http://192.168.201.131:8080/login/?next=http%3A%2F%2F192.168.201.131%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow-web-854d8b469-7z2jq airflow-web 127.0.0.1 - - [02/Feb/2021:12:40:57 +0000] "GET /static/dist/materialIcons.c86800f70eece0ad5c3e.css HTTP/1.1" 200 0 "http://192.168.201.131:8080/login/?next=http%3A%2F%2F192.168.201.131%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow-web-854d8b469-7z2jq airflow-web 127.0.0.1 - - [02/Feb/2021:12:40:57 +0000] "GET /static/appbuilder/css/flags/flags16.css HTTP/1.1" 200 0 "http://192.168.201.131:8080/login/?next=http%3A%2F%2F192.168.201.131%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow-web-854d8b469-7z2jq airflow-web 127.0.0.1 - - [02/Feb/2021:12:40:57 +0000] "GET /static/dist/main.559baa8766c31899215b.css HTTP/1.1" 200 0 "http://192.168.201.131:8080/login/?next=http%3A%2F%2F192.168.201.131%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
```

It is using this image: docker.io/bitnami/airflow:2.0.0-debian-10-r8. Could you confirm that you are using the same?

**Comment by StephanZaat** [comment] 2021-02-02 12:58
I realise that we have hijacked an issue about Airflow 2.0, but we seem to have this issue with V1 of Airflow:
I'm using this version: 1.10.14-debian-10-r37

**Comment by carrodher** [comment] 2021-02-03 08:08
Sorry for the misunderstanding, finally, I was able to reproduce the issue using docker-compose and the 1.X version:

**Airflow 1.X**:
```
airflow_1            | 172.29.0.1 - - [03/Feb/2021:07:56:30 +0000] "GET /static/ HTTP/1.1" 404 3868 "http://127.0.0.1:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 172.29.0.1 - - [03/Feb/2021:07:56:30 +0000] "GET /static/ HTTP/1.1" 404 3868 "http://127.0.0.1:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 172.29.0.1 - - [03/Feb/2021:07:56:30 +0000] "GET /static/ HTTP/1.1" 404 3868 "http://127.0.0.1:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 172.29.0.1 - - [03/Feb/2021:07:56:30 +0000] "GET /static/ HTTP/1.1" 404 3868 "http://127.0.0.1:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 172.29.0.1 - - [03/Feb/2021:07:56:30 +0000] "GET /static/ HTTP/1.1" 404 3868 "http://127.0.0.1:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 172.29.0.1 - - [03/Feb/2021:07:56:30 +0000] "GET /static/ HTTP/1.1" 404 3868 "http://127.0.0.1:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
```

![Screenshot 2021-02-03 at 08 57 47](https://user-images.githubusercontent.com/13216600/106716643-f9ae9980-65fe-11eb-90c2-953d69574255.png)

**Airflow 2.X**:
```
airflow_1            | 192.168.0.1 - - [03/Feb/2021:08:00:09 +0000] "GET /static/dist/airflowDefaultTheme.42f8d9f03e53e5b06087.css HTTP/1.1" 200 0 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 192.168.0.1 - - [03/Feb/2021:08:00:09 +0000] "GET /static/dist/materialIcons.c86800f70eece0ad5c3e.css HTTP/1.1" 200 0 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 192.168.0.1 - - [03/Feb/2021:08:00:09 +0000] "GET /static/dist/main.559baa8766c31899215b.css HTTP/1.1" 200 0 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 192.168.0.1 - - [03/Feb/2021:08:00:09 +0000] "GET /static/dist/bootstrap-datetimepicker.min.css HTTP/1.1" 200 0 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 192.168.0.1 - - [03/Feb/2021:08:00:09 +0000] "GET /static/dist/flash.82c9e653b17d76b0b572.css HTTP/1.1" 200 0 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 192.168.0.1 - - [03/Feb/2021:08:00:09 +0000] "GET /static/dist/loadingDots.f9d109f104217ec97cea.css HTTP/1.1" 200 0 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
airflow_1            | 192.168.0.1 - - [03/Feb/2021:08:00:09 +0000] "GET /static/dist/main.559baa8766c31899215b.js HTTP/1.1" 200 0 "http://127.0.0.1:8080/login/?next=http%3A%2F%2F127.0.0.1%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
```
![Screenshot 2021-02-03 at 09 00 32](https://user-images.githubusercontent.com/13216600/106716702-0a5f0f80-65ff-11eb-813c-f9d6963c8ed5.png)

----------------------------------------------

It seems there is an issue with the latest tags in version 1.X, we will investigate the issue

**Comment by javsalgar** [comment] 2021-02-04 08:28
Hi,

Just a quick note to let you know that `-r41` of the Airflow 1 container should have the issue fixed. Could you please check?

**Comment by StephanZaat** [comment] 2021-02-04 16:07
Yes! It is fixed. Thank you!
